name: MacOS

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        compiler: [g++, clang++]
        flags: [-std=c++20]
        optimize: [-O2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build and test
      env:
        CXX: ${{ matrix.compiler }}
        CXXFLAGS: ${{ matrix.flags }} ${{ matrix.optimize }}
      run: |
        mkdir build && cd build && cmake -DGTL_BUILD_TESTS=ON -DGTL_BUILD_EXAMPLES=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && make test
