name: Windows

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        flags: ["/std:c++latest"]
        optimize: [/O2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build and test
      env:
        CXX: ${{ matrix.compiler }}
        CXXFLAGS: ${{ matrix.flags }} ${{ matrix.optimize }}
        CTEST_OUTPUT_ON_FAILURE: 1
      run: |
        cmake -Bbuild -DGTL_BUILD_TESTS=ON -DGTL_BUILD_EXAMPLES=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=Release && cmake --build build --target ALL_BUILD && cmake --build build --target RUN_TESTS
